language: generic
sudo: false

branches:
  only:
    - master
    - /^\d+\.\d+.*$/

os:
  - linux
  - osx

env:
  global:
    secure: Vf0mo4VkI/AgebH9WmFSzwj7sEKCrydW3H0EOegvx1tNLieq9i38ZTyoW/srLX2N60T9xuf+J8+Ntwo978/Iu69O+SD4ghCBa4SThS+b7R2wtRXa3TL3uV1n1GRY8ybCl1bOARQ1wgoPYOQUZ6oAIrmAUjeM7g2Y63vp1y8nVYJPFjJuToJ3JNiB+l0FUA43MuHMhVFaO0U6vwbkmOPc5a4hk+NQYCCTa36XRb5BscQwzfhFKsQ295tHxmK5ZFiU8PhzK/fRyKUnkDhGa0PyQnHoBztHjJgHmcMQOfvgMctOZiFFgQP6yiwV5BzB4eYYH7eDk5rbyK5PT3ptsPJQmLrjFCDyp6lbRMRvyvdN08Rw3mjQyPhqeo9UNwNc3iFHHBSNqtXx+AtZKxYeJru3eLH6B+FgBdw6fy+Wire1sRzPLnIzQbaG70siIDS6nVlyynaxXfpbrzEJYH8cSib9XB2YqK+fHmfDa21n4U6aVJuQdC5Z0NudWqp3utNvWlwMbVLyffMgZjfLyfhu6mVyzWpYWJ5wehveBP4gd3eMhihOco0SzBicvbzE5eS2ndQPIGv/PtC3t/mLWMIRo72hnaxhhxWbeeh7K++idJRz7PMiIXwP3hKFLNc8RfbLriKBponK29Vv3aVWN2zc2NyWr9kKL9rt+6kAmj69gbRmQHA=
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7
    - PYTHON_VERSION=3.8

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  # Fix the conda version before full activation
  - source $HOME/miniconda/bin/activate
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda no
  # The tests need to see the Python kernel in the root environment
  - conda install conda-verify conda-build ipykernel anaconda-client
  # We need to create additional environments to fully test the logic,
  # including an R kernel, a Python kernel, and environment names with at
  # least one non-ASCII character and one space. We also need one environment
  # installed in a non-default environment location. Because AppVeyor is
  # difficult to work with for non-ASCII content we're using env files.
  - conda env create -f conda-recipe/testenv1.yaml -p $HOME/.conda/envs/test_env1
  - conda env create -f conda-recipe/testenv2.yaml
  - rm -f $HOME/.conda/environments.txt
  - conda info -a

script:
  - conda build conda-recipe --python=$PYTHON_VERSION --no-long-test-prefix

deploy:
  # Upload to main label for tagged master builds
  - provider: script
    skip_cleanup: true
    on:
      branch: master
      tags: true
    script: anaconda --verbose --token $ANACONDA_TOKEN upload --user jupycon $HOME/miniconda/conda-bld/*/*.tar.bz2 --force
  # Upload to dev label for untagged master builds
  - provider: script
    skip_cleanup: true
    on:
      branch: master
      tags: false
    script: anaconda --verbose --token $ANACONDA_TOKEN upload --user jupycon --label dev $HOME/miniconda/conda-bld/*/*.tar.bz2 --force
